### ISSUE TITLE
[FEATURE] Add the Polygon Academy

### ISSUE THREAD

**Issue by mkubdev** [web3community/blockchain-dev-path#31]
### Detailed description

We should add the [Polygon Academy](https://github.com/Polygon-Academy) to this repos. 🤓 

### Context

Blockchains providers sometimes had their own academy, good ressources to learn the chain specifications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unnikrishnan2002** [comment]
Can I do that ?

**Comment by KukretiShubham** [comment]
Go ahead

**Comment by unnikrishnan2002** [comment]
> Go ahead

I have to add it  [here](https://github.com/web3community/blockchain-dev-path/blob/main/free-training/training.md) right ?

**Comment by Panquesito7** [comment]
> > Go ahead
> 
> I have to add it [here](https://github.com/web3community/blockchain-dev-path/blob/main/free-training/training.md) right ?

Yep! :)

**Comment by mkubdev** [comment]
Thanks @unnikrishnan2002 :)
