### ISSUE TITLE
[BUG] Update footer + header logo

### ISSUE THREAD

**Issue by mkubdev** [web3community/blockchain-dev-path#44]
### Description of the bug

Replace with the new logo.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/50140834/189099313-807521e2-6f6d-4a53-8778-0b86e76d72a9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
@Panquesito7  you want this issue to be assigned to you?
